### ISSUE TITLE
Expanding abbreviation does not work with Brackets 22

### ISSUE THREAD

**Issue by adam-lynch** [emmetio/brackets-emmet#10]
For me at least, the shortcuts and the menu actions don't do anything.

I found this error in the developer console:

> **32 _times_** - Uncaught TypeError: Object #<Object> has no method 'compoundChange' _........./Brackets/extensions/user/emmet/main.js:1_

**Comment by CodeAmend** [comment]
When I click ctrl-alt-enter nothing happens. When I click ctrl-shift-G nothing happens. When I click ctrl-shift-alt-enter all at once the abbreviation text box shows up at bottom until I release even one key. If I go to the menu and manually select abbreviation expand. Nothing happens. What can be wrong?
