### ISSUE TITLE
Emmet is not working

### ISSUE THREAD

**Issue by salehST** [emmetio/brackets-emmet#100]
i couldn't install the emmet at 1st. and when i installed it emmet isn't working.
![problem](https://cloud.githubusercontent.com/assets/13993598/12752117/0c44eeec-c9eb-11e5-93bf-65a944b44cbd.jpg)

**Comment by sergeche** [comment]
Please describe what you mean by “not working”

**Comment by salehST** [comment]
when i am trying to execute the Ctrl+E the code isn't creating any div's with class name...hope this helps u to understand. you can see the code in the picture that, i want to execute [ div.row>div.skill-bar ]

**Comment by sergeche** [comment]
You screenshot clearly says that shortcut for expanding abbreviations is Ctrl+Alt+Enter

**Comment by salehST** [comment]
Thank you, i am new user to brackets. Didn't noticed that. Thank you aging..lol

**Comment by MelissaMenard** [comment]
Searched for hours to get that to work! Thanks
