### ISSUE TITLE
hotkeys - conflict

### ISSUE THREAD

**Issue by IgorNovozhilov** [emmetio/brackets-emmet#101]
sprint 6 build 1.6.0-16680 (release 3df0ac6fa) 

Emmet 1.2.2

Cannot assign Ctrl-Alt-B to io.emmet.balance_outward. It is already assigned to bb.beautify.beautify
/command/KeyBindingManager.js:749

Cannot assign Ctrl-Shift-Up to io.emmet.increment_number_by_1. It is already assigned to edit.lineUp
/command/KeyBindingManager.js:749

Cannot assign Ctrl-Shift-Down to io.emmet.decrement_number_by_1. It is already assigned to edit.lineDown
##

**Comment by Mte90** [comment]
very annoying...

**Comment by IgorNovozhilov** [comment]
неактуально
