### ISSUE TITLE
Extra new line is added when I press Enter

### ISSUE THREAD

**Issue by john-cj** [emmetio/brackets-emmet#103]
To reproduce:

Create blank html file, press Enter 2 times. 

![emmet2](https://cloud.githubusercontent.com/assets/18004961/14782031/2e1dc710-0aef-11e6-90a6-2a37f2d1974a.png)

It's all okay, you are on the line 3.

Now, press Enter again and the error is happened - you are on the line 5. The line 4 is skipped:

![emmet3](https://cloud.githubusercontent.com/assets/18004961/14782051/60fcea12-0aef-11e6-84e8-460301fc694c.png)

You also may press Enter again, and the line 6 also will be skipped, you will be at the line 7:

![emmet4](https://cloud.githubusercontent.com/assets/18004961/14782065/80ccf9f4-0aef-11e6-8ce2-ae522c4c0b95.png)
##

**Comment by samyakb** [comment]
![screenshot from 2017-04-27 19-51-12](https://cloud.githubusercontent.com/assets/16825207/25487813/d684ec5e-2b54-11e7-82d4-4ac8b940cb86.png)
variable `activeEditor` is already defined for `expand_abbreviation_with_tab`

**Comment by samyakb** [comment]
I think we should edit `var activeEditor` in `if` loop of `insert_formatted_line_break` to `lineActiveEditor`
