### ISSUE TITLE
Emmet not working on Brackets 1.14

### ISSUE THREAD

**Issue by FelipeSharkao** [emmetio/brackets-emmet#141]
I installed Emmit from Brackets itself, but the Emmet tab don't shows up, and any of its commands works. I'm using Brackets 1.14 build 1.14.2-17770 on Windows 10 and I have installed Emmet 1.2.2.

**Comment by Just-Tamizha** [comment]
You solve that problem ?

**Comment by FelipeSharkao** [comment]
Man, didn't remember of this. No, I didn't solve the problem, but I switched to Linux and VS Code, for other reasons. I'll be closing the issue, since it is not relevant anymore.
