### ISSUE TITLE
Emmet does not install or appear in menu

### ISSUE THREAD

**Issue by xtoq** [emmetio/brackets-emmet#51]
On a fresh install of Brackets sprint 39, Emmet is not working. I updated Emmet, still not working. I removed all other extensions except Emmet and it still does not work. I completely uninstalled Brackets and reinstalled with only Emmet, still nothing. I've manually installed, I've installed from the URL, and I've used the extension manager; nothing.

Using Windows 7 64 bit. Please let me know if there is anything else I can try or provide. Thank you!

**Comment by krushank** [comment]
hi,

just go in Debug -> Reload with extensions... that did the trick for me !!

happy coding..
