### ISSUE TITLE
Parse snippets inside of <?php ?> -tags?

### ISSUE THREAD

**Issue by circlewaves** [emmetio/brackets-emmet#55]
Hello,

I try to add some custom php-snippets, but for some reason it doesn't work inside of php-tags.
For example, I have json file with my custom-snippets (file snippets-php.json):

> {
> "html": {
>    "snippets": {
>          "mysnippet": "Some text goes here",
>    }
>  }
> }

This snippet works fine if I try to expand "mysnippet" outside of php-tags, but inside of php tags "mysnippet" just converts into <mysnippet></mysnippet>, for example file index.php:

> mysnippet // this converts into "Some text goes here"
> <?php
> mysnippet // This converts into  <mysnippet></mysnippet>
> ?>

I have tried a lot of solutions, but unfortunately, without success, e.g.

> {
> "php": {
>    "snippets": {
>          "mysnippet": "Some text goes here",
>    }
>  }
> }

Could someone help me?

Thanks in advance!

**Comment by wonkler** [comment]
@sergeche Do you know how Brackets identifies JavaScript syntax in this case?

I have tried the following to add JS snippets with no luck:
```javascript
{
    "js": {
        "snippets": {
            "mysnippet": "Some text goes here"
        }
    }
}
```javascript

Also,

```javascript
{
    "javascript": {
        "snippets": {
            "mysnippet": "Some text goes here"
        }
    }
}
```javascript

Any solution would be very appreciated!
