### ISSUE TITLE
Emmet does not self-close tags when doctype is set to XHTML Transitional in Adobe Brackets

### ISSUE THREAD

**Issue by skube** [emmetio/brackets-emmet#75]
Does anyone else have this issue when using Adobe Brackets and setting the doctype to:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
```

Then using Emmet to expand a self-closing tag such as an `img` tag, results in:

```html
<img src="" alt="">
```

Instead of what I get in Sublime Text:
```html
<img src="" alt="" />
```

I'm not exactly sure if it's an Emmet issue or Brackets (or perhaps even something I've set inadvertently). I [submitted an issue](https://github.com/adobe/brackets/issues/10678) to the Brackets team and they suggested the issue is with Emmet.

Using Brackets (v 8f82e2a97) on OS X with Emmet installed but it also occurs on Windows version of Brackets.

**Comment by lewishowles** [comment]
Have you already set HTML to use XHTML style in your custom snippets file? This is the option that self closes tags, among other things, I believe - I don't think it looks at the doctype at all. So in `snippets.json`

    {
    	"html": {
	    	"profile": "xhtml",
	    }
    }

and then tell Emmet in its preferences where to find that file. I know mine self-closes tags like this (in all documents).

**Comment by skube** [comment]
Well I was using the exact same custom snippets file for both Brackets and Sublime Text so I was confused why it worked in one and not the other. However, you are correct changing the `profile` to `xhtml` works in both now.
