### ISSUE TITLE
Shortcut "wrap_with_abbreviation" no longer works

### ISSUE THREAD

**Issue by LeG3nDz** [emmetio/brackets-emmet#78]
Hi,

Since update brackets, the "wrap_with_abbreviation" shortcut no longer works. I've check on brackets.js, and i've this :

        "io.emmet.wrap_with_abbreviation": {
            "commandID": "io.emmet.wrap_with_abbreviation",
            "key": "Ctrl-Shift-A"
        },

But if i select my text and push ctrl-shift-a, nothing happens.

Any idea ?

Thank you :)

**Comment by iampeterbanjo** [comment]
I am experiencing the same issue and I am using a Mac with Brackets Release 1.2 build 1.2.0-15697 (release 8f82e2a97) build timestamp: Sun Feb 22 2015 22:34:50 GMT-0800

**Comment by sergeche** [comment]
Try to use menu item — dies it works? There might be some other extension that steals this shortcut

**Comment by LeG3nDz** [comment]
Hi,

With the menu item, worked. I've check on my brackets.json, and i've have just one shortcut with Ctrl-Shift-A, and it's for emmet.

**Comment by sergeche** [comment]
It’s not about your `brackets.json`, it’s about another extension that may override the same shortcut

**Comment by LeG3nDz** [comment]
Aaah yes, indeed ! I found what extension problem : Brackets simple todo. I will inform the editor ;)

Thank you ;)

**Comment by iampeterbanjo** [comment]
Yes! Removing the simple todo extension fixes this. Thanks. :-)

**Comment by LeG3nDz** [comment]
Not need remove simple todo extension, juste chang shortcut on settings ;)
