### ISSUE TITLE
Regression with jsx support

### ISSUE THREAD

**Issue by sprintr** [emmetio/brackets-emmet#80]
Recently, Emmet added support for jsx. It has caused a regression for devs who don't use jsx or use `.jsx` instead of `.js`. It would be nice to provide a preference to disable `jsx` expanding in `.js` files or limit it to `.jsx` only.

Here is a screenshot of it.

![emmet-js-bug](https://cloud.githubusercontent.com/assets/3390089/6966851/3d8e8204-d975-11e4-95ad-af2d1cd37cb2.png)

**Comment by marlonmleite** [comment]
+1
--
Autocomplete in .js error, my plugins will not work properly because of the applicability of Emmet in .js files.

Solution: Create one menu to disable Emmet .js files or 1 input to put the extensions that you want is not applied Emmet.

**Comment by sergeche** [comment]
Fixed in v1.2.2
